# Generated by Django 4.2.21 on 2026-04-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_refund_ordertimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('cbd', 'CBD / City Center'), ('suburb', 'Suburbs'), ('upcountry', 'Upcountry')], max_length=20)),
                ('counties', models.JSONField(default=list, help_text='List of county names this zone covers')),
                ('cities', models.JSONField(blank=True, default=list, help_text='Optional finer-grain city/area names')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order subtotal above which shipping is free. Leave blank to disable.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority zones are matched first. Use for city overrides within a county.')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, help_text='Zone used to calculate shipping for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippingzone'),
        ),
    ]
