# Generated by Django 5.2.8 on 2025-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_address_id_alter_order_id_alter_orderitem_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
    ]
