# Generated by Django 4.2.21 on 2026-03-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_status_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing'), ('accessories', 'Accessories')], max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing'), ('accessories', 'Accessories')], max_length=20),
        ),
    ]
