# Generated by Django 4.2.21 on 2026-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_type_alter_size_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing'), ('Accessories', 'Accessories')], max_length=20),
        ),
    ]
