# Generated by Django 5.2.8 on 2025-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20251022_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesatransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
